app/accounts/urls.py
from django.urls import include, path
from accounts.views import MyProfileView
from django.contrib.auth import views as auth_views
from accounts import views
from accounts.views import PassSuccssesViews, SingUpView, ActivateView

app_name = 'accounts'
urlpatterns = [

    path('my-profile/<int:pk>', MyProfileView.as_view(), name="my-profile"),
    path("change-password/pass_success/", PassSuccssesViews.as_view(), name="pass-success"),
    path('change-password/<int:pk>',
         auth_views.PasswordChangeView.as_view(
             template_name="password_change.html",
             success_url='pass_success/'  # не могу поставить другую ссылку :(
         ),
         name="change-password"),
    # path('password_reset/<int:pk>', auth_views.PasswordResetView(), name='password_reset'
    path('sing-up/', SingUpView.as_view(), name="sing-up"),
    path('activate/<uuid:username>', ActivateView.as_view(), name="activate"),

]

app/currency/urls.py
from django.contrib import admin
from django.urls import path
from currency.views import RateCreateViews
from currency.views import Rate2CreateViews
from currency.views import Rate2ListViews
from currency.views import RateListViews
from currency.views import KursListViews
from currency.views import RateUpdateViews
from currency.views import Rate2UpdateViews
from currency.views import RateDetailViews
from currency.views import Rate2DetailViews
from currency.views import RateDeleteViews
import debug_toolbar
from django.conf import settings
from django.urls import include, path

urlpatterns = [
    path('rate/', RateListViews.as_view(), name="rate-list"),
    path('rate2/', Rate2ListViews.as_view(), name="rate-list2"),
    path('kurs/', KursListViews.as_view(), name="kurs-list"),
    path('rate/create/', RateCreateViews.as_view(), name="rate-create"),
    path('rate/create2/', Rate2CreateViews.as_view(), name="rate-create2"),
    path('rate/details/<int:pk>', RateDetailViews.as_view(), name="rate-details"),
    path('rate/details2/<int:pk>', Rate2DetailViews.as_view(), name="rate-details2"),
    path('rate/update/<int:pk>', RateUpdateViews.as_view(), name="rate-update"),
    path('rate/update2/<int:pk>', Rate2UpdateViews.as_view(), name="rate-update2"),
    path('rate/delete/<int:pk>', RateDeleteViews.as_view(), name="rate-delete"),

]

app/settings/urls.py
from django.contrib import admin
from django.urls import path
from currency.views import response_codes
from currency.views import IndexViews
from currency.views import GenPassViews
from currency.views import ContactUsViews
# from django.contrib.auth.urls
import debug_toolbar
from django.conf import settings
from django.urls import include, path

urlpatterns = [
    path('', IndexViews.as_view(), name="index"),
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('gen/', GenPassViews.as_view()),
    path('response/', response_codes),
    path("currency/", include("currency.urls")),
    path('contact_us_create/', ContactUsViews.as_view(), name="contact_us_create"),
    path('auth/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls'))


]

app/currency/models.py
from django.db import models
from currency import model_choises as MCH


class SourceModel(models.Model):
    name = models.CharField(max_length=24)


class Rate(models.Model):
    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=21)
    salary = models.DecimalField(max_digits=6, decimal_places=2)  # 1234.56
    state = models.CharField(max_length=2)
    date = models.DateTimeField(auto_now_add=True)
    # car = models.CharField(max_length=10)
    child = models.BooleanField(max_length=5)


class ContactUs(models.Model):
    email_to = models.EmailField()
    subject = models.CharField(max_length=255)
    body = models.CharField(max_length=2056)
    date = models.DateTimeField(auto_now_add=True)


class Rate2(models.Model):
    sale = models.DecimalField(max_digits=5, decimal_places=2)
    buy = models.DecimalField(max_digits=5, decimal_places=2)
    # source = models.CharField(max_length=16)
    source = models.ForeignKey(SourceModel, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    type = models.CharField(max_length=3, choices=MCH.RATE2_TYPES)


class ResponseLog(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    statuscode = models.PositiveSmallIntegerField()
    path = models.CharField(max_length=256)
    responsetime = models.PositiveSmallIntegerField()

app/currency/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from currency.password_gen import password_generates
from currency.models import Rate
from currency.models import Rate2
from currency.models import ContactUs
from currency.form import RateForms
from currency.form import Rate2Forms
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DetailView
from django.views.generic import DeleteView
from django.views.generic import TemplateView
from django.core.mail import send_mail
# так делать не надо
# from settings import settings
from django.conf import settings


# def gen_pass(request):
#     password_len = 10
#     password = password_generates(password_len)
#     text = {"pass": password}
#     return render(request, "gen.html", context=text)


class GenPassViews(TemplateView):
    template_name = "gen.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        password_len = 10
        password = password_generates(password_len)
        context["pass"] = password
        return context


def response_codes(request):
    return HttpResponse("Response", status=201)


#
# def raid_list(request):
#     rates = Rate.objects.all()
#     text = {"message": rates}
#     return render(request, "r_list.html", context=text)


class RateListViews(ListView):
    model = Rate
    template_name = "r_list.html"

    def get(self, request, *args, **kwargs):
        print(request.COOKIES)
        return super().get(request, *args, **kwargs)


class Rate2ListViews(ListView):
    model = Rate2
    template_name = "r_list2.html"


class KursListViews(ListView):
    model = Rate2
    template_name = "kurs_list.html"


# def index(request):
#     return render(request, "index.html")


class IndexViews(TemplateView):
    template_name = "index.html"


# def r_create(request):
#     forms = RateForms()
#     if request.method == 'POST':
#         form = RateForms(request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect('/rate/')
#     elif request.method == "GET":
#         forms = RateForms()
#     text = {"form": forms}
#     # breakpoint()
#     return render(request, "r_create.html", context=text)


class RateCreateViews(CreateView):
    model = Rate
    template_name = "r_create2.html"
    form_class = RateForms
    success_url = reverse_lazy("rate-list")


class Rate2CreateViews(CreateView):
    model = Rate2
    template_name = "r_create2.html"
    form_class = Rate2Forms
    success_url = reverse_lazy("rate-list2")


# def r_details(request, rate_id):
#     rate1 = get_object_or_404(Rate, id=rate_id)
#     text = {"object": rate1}
#     return render(request, "r_details.html", context=text)


class RateDetailViews(DetailView):
    model = Rate
    template_name = "r_details.html"


class Rate2DetailViews(DetailView):
    model = Rate2
    template_name = "r_details2.html"


# def r_update(request, rate_id):
#     rate1 = get_object_or_404(Rate, id=rate_id)
#     if request.method == 'POST':
#         form = RateForms(request.POST, instance=rate1)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect('/rate/')
#     elif request.method == "GET":
#         forms = RateForms(instance=rate1)
#     text = {"form": forms}
#
#     return render(request, "r_update.html", context=text)


class RateUpdateViews(UpdateView):
    model = Rate
    form_class = RateForms
    success_url = reverse_lazy("rate-list")
    template_name = "r_update.html"


class Rate2UpdateViews(UpdateView):
    model = Rate2
    form_class = Rate2Forms
    success_url = reverse_lazy("rate-list2")
    template_name = "r_update2.html"


# def r_delete(request, rate_id):
#     rate1 = get_object_or_404(Rate, id=rate_id)
#     if request.method == 'POST':
#         rate1.delete()
#         return HttpResponseRedirect('/rate/')
#     text = {"object": rate1}
#
#     return render(request, "r_delete.html", context=text)

class RateDeleteViews(DeleteView):
    model = Rate
    success_url = reverse_lazy("rate-list")
    template_name = "r_delete.html"


class ContactUsViews(CreateView):
    model = ContactUs
    template_name = "contact_us_create.html"
    success_url = reverse_lazy("index")
    fields = ("email_to", "subject", "body")

    def form_invalid(self, form):
        print("ДУРИШЬ ТЫ МЕНЯ")
        return super().form_invalid(form)

    def form_valid(self, form):
        print("Всё огонёк!")
        subject = form.cleaned_data["subject"]
        body = form.cleaned_data["body"]
        email_to = form.cleaned_data["email_to"]
        full_email_body = f"""
        email from: {email_to}
        body: {body}
        """
        from currency.tasks import contact_us
        contact_us.apply_async(args=(subject,), kwargs={"body": full_email_body})
        return super().form_valid(form)

app/currency/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

</head>
<body>
{%include 'includes/nav.html'%}
<div class="container">

    {%block main_content%}
    {%endblock%}
</div>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/currency/templates/contact_us_create.html
{%extends 'base.html'%}
{%block main_content%}
contact us
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit">шо там?</button>
</form>

<form>
    <div class="form-group">
        <label for="exampleFormControlInput1">Email address</label>
        <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
    </div>
    <div class="form-group">
        <label for="formGroupExampleInput">Example label</label>
        <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input placeholder">
    </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Example textarea</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
    </div>
    <div class="col-auto my-1">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
{%endblock%}

app/currency/templates/gen.html
{%extends 'base.html'%}
{%block main_content%}
{{pass}}
{%endblock%}

app/currency/templates/index.html
{%extends 'base.html'%}

{%block main_content%}

<div class="row">
    <div class="col">Привет из индекса 1</div>
    <!--        <div class="col">Привет из индекса 2</div>-->
    <!--        <div class="col">Привет из индекса 3</div>-->
    <!--        <div class="col">Привет из индекса 4</div>-->
</div>

{%endblock%}

app/currency/templates/kurs_list.html
{%extends 'base.html'%}
{%block main_content%}
<a href="{%url 'rate-create2'%}">create rate</a></br>
{%for i in rate2_list%}
id:{{i.id}}
</br>
{{i.source}} {{i.type}}</br>
продажа {{i.sale}}
покупка {{i.buy}}
</br>
{{i.created}}
</br>
</br>
<!--<a href="{%url 'rate-details2' pk=i.pk%}">Details</a>-->
<!--<a href="{%url 'rate-update2' pk=i.pk%}">UPDATE</a>-->
<!--<a href="{%url 'rate-delete' pk=i.pk%}">DELETE</a>-->
{%endfor%}
{%endblock%}
<!--Rate2.objects.filter(type=currency_type, source=source).order_by("created").last()-->

<!--id {{i.id}} {{i.type}} продажа {{i.sale}} покупка {{i.buy}} место {{i.source}}-->

app/currency/templates/r_create.html
{%extends 'base.html'%}
{%block main_content%}
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit">шо там?</button>
</form>
{%endblock%}

app/currency/templates/r_create2.html
{%extends 'base.html'%}
{%block main_content%}
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit">шо там?</button>
</form>
{%endblock%}

app/currency/templates/r_delete.html
{%extends 'base.html'%}
{%block main_content%}
точно удалить{{object.id}}?
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit">ПОШЕЛ ОТ СЮДА!</button>
</form>
{%endblock%}

app/currency/templates/r_details.html
{%extends 'base.html'%}
{%block main_content%}
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">name</th>
      <th scope="col">surname</th>
      <th scope="col">salary</th>
      <th scope="col">state</th>
      <th scope="col">child</th>
      <th scope="col">date</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">{{object.id}}</th>
      <td>{{object.name}}</td>
      <td>{{object.surname}}</td>
      <td>{{object.salary}}</td>
      <td>{{object.state}}</td>
      <td>{{object.child}}</td>
      <td>{{object.date}}</td>
    </tr>
  </tbody>
</table>
{%endblock%}

app/currency/templates/r_details2.html
{%extends 'base.html'%}
{%block main_content%}
ID = {{object.id}}</br>
sale = {{object.sale}}</br>
buy = {{object.buy}}</br>
source = {{object.source}}</br>
created = {{object.created}}</br>
type = {{object.type}}</br>
{%endblock%}

app/currency/templates/r_list.html
{%extends 'base.html'%}
{%block main_content%}
<a href="{%url 'rate-create'%}" type="button" class="btn btn-primary">create rate</a>
<!--{%for i in rate_list%}-->
<!--ID {{i.id}} NAME {{i.name}} SURNAME {{i.surname}}-->
<!--{% if request.user.is_authenticated%}-->
<!--    <a href="{%url 'rate-details' pk=i.pk%}">Details</a>-->
<!--{% endif %}-->
<!--{% if request.user.is_superuser%}-->
<!--<a href="{%url 'rate-update' pk=i.pk%}">UPDATE</a>-->
<!--<a href="{%url 'rate-delete' pk=i.pk%}">DELETE</a>-->
<!--{% endif %}-->
<!--</br>-->
<!--{%endfor%}-->
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">id</th>
        <th scope="col">name</th>
        <th scope="col">surname</th>
        {% if request.user.is_authenticated%}
        <th scope="col">actions</th>
        {% endif %}
    </tr>
    </thead>
    <tbody>
    {%for i in rate_list%}
    <tr>
        <td>{{i.id}}</td>
        <td>{{i.name}}</td>
        <td>{{i.surname}}</td>
        {% if request.user.is_authenticated%}
        <td>

                <div class="dropdown">
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                       data-toggle="dropdown" aria-expanded="false">
                        Actions
                    </a>

                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{%url 'rate-details' pk=i.pk%}">Deteils</a>
                        <a class="dropdown-item" href="{%url 'rate-update' pk=i.pk%}">Update</a>
                        <a class="dropdown-item" href="{%url 'rate-delete' pk=i.pk%}">Delete</a>
                    </div>
                </div>

            </td>
        {% endif %}
    </tr>
    {%endfor%}
    </tbody>

</table>
{%endblock%}

app/currency/templates/r_list2.html
{%extends 'base.html'%}
{%block main_content%}
<a href="{%url 'rate-create2'%}">create rate</a></br>
{%for i in rate2_list%}
ID {{i.id}} {{i.get_type_display}} продажа {{i.sale}} покупка {{i.buy}} СОУС {{i.source}}
<a href="{%url 'rate-details2' pk=i.pk%}">Details</a>
<a href="{%url 'rate-update2' pk=i.pk%}">UPDATE</a>
<!--<a href="{%url 'rate-delete' pk=i.pk%}">DELETE</a>-->
</br>
{%endfor%}
{%endblock%}

app/currency/templates/r_update.html
{%extends 'base.html'%}
{%block main_content%}
<form method="post">
    {%csrf_token%}
    {{form.as_p}}



    <button type="submit">поменяй??</button>
</form>
{%endblock%}

app/currency/templates/r_update2.html
{%extends 'base.html'%}
{%block main_content%}
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit">поменяй??</button>
</form>
{%endblock%}