app/accounts/urls.py
from django.urls import include, path
from accounts.views import MyProfileView
from django.contrib.auth import views as auth_views
from accounts import views
from accounts.views import PassSuccssesViews, SingUpView, ActivateView

app_name = 'accounts'
urlpatterns = [

    path('my-profile/<int:pk>', MyProfileView.as_view(), name="my-profile"),
    path("change-password/pass_success/", PassSuccssesViews.as_view(), name="pass-success"),
    path('change-password/<int:pk>',
         auth_views.PasswordChangeView.as_view(
             template_name="password_change.html",
             success_url='pass_success/'  # не могу поставить другую ссылку :(
         ),
         name="change-password"),
    # path('password_reset/<int:pk>', auth_views.PasswordResetView(), name='password_reset'
    path('sing-up/', SingUpView.as_view(), name="sing-up"),
    path('activate/<uuid:username>', ActivateView.as_view(), name="activate"),

]

app/settings/urls.py
from django.contrib import admin
from django.urls import path
from currency.views import response_codes
from currency.views import IndexViews
from currency.views import GenPassViews
from currency.views import ContactUsViews
# from django.contrib.auth.urls
import debug_toolbar
from django.conf import settings
from django.urls import include, path

urlpatterns = [
    path('', IndexViews.as_view(), name="index"),
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('gen/', GenPassViews.as_view()),
    path('response/', response_codes),
    path("currency/", include("currency.urls")),
    path('contact_us_create/', ContactUsViews.as_view(), name="contact_us_create"),
    path('auth/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls'))


]

app/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    email = models.EmailField('email address', blank=True, unique=True)

app/accounts/forms.py
import uuid

from django import forms
from django.urls import reverse

import settings.settings
from accounts.models import User
from accounts.tasks import activate_email


class SingUpForms(forms.ModelForm):
    password1 = forms.CharField(max_length='200', widget=forms.PasswordInput())
    password2 = forms.CharField(max_length='200', widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = (
            "email",
            'password1',
            'password2',
        )

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['password1'] != cleaned_data['password2']:
            # raise forms.ValidationError('ПАРОЛЬ НЕСОВПАЛ!!!!')
            self.add_error('password2', 'ПАРОЛЬ НЕСОВПАЛ!!!!')
        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.is_active = False
        instance.username = str(uuid.uuid4())
        instance.set_password(self.cleaned_data['password2'])
        # Здесь был бы реализован процесс отправки ссылки на почту
        # print(f"http://localhost:8000/accounts/activate/{instance.username}")
        activate_email.delay(
            f"{settings.settings.HTTP_SCHEMA}://{settings.settings.DOMEN}"
            f"{reverse('accounts:activate', args=[instance.username])}",
            instance.email

        )
        if commit:
            instance.save()
        return instance

app/accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView, View, RedirectView
from django.views.generic import ListView
# Create your views here.
from accounts.models import User
from accounts.forms import SingUpForms
from django.views.generic import TemplateView
from django.contrib import messages


class PassSuccssesViews(TemplateView):
    template_name = "password_success.html"


class MyProfileView(LoginRequiredMixin, UpdateView):
    queryset = User.objects.all()
    fields = ('first_name', 'last_name')
    success_url = reverse_lazy("index")
    template_name = "my_profile.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(id=self.request.user.id)
        return queryset


class SingUpView(CreateView):
    model = User
    template_name = "sing_up.html"
    form_class = SingUpForms
    success_url = reverse_lazy("index")

    def form_valid(self, form):
        messages.info(self.request, "зарегенился, а теперь сходи на почту")
        return super().form_valid(form)


class ActivateView(RedirectView):
    pattern_name = "index"

    def get_redirect_url(self, *args, **kwargs):
        username = kwargs.pop("username")
        print(f"-----------------------------------username = {username}")

        user = get_object_or_404(User, username=username, is_active=False)
        user.is_active = True
        user.save(update_fields=('is_active',))
        messages.info(self.request, 'активироватовл ирывпяилияывачполиоваыиатвычптвч')

        return super().get_redirect_url(*args, **kwargs)

app/accounts/templates/message.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

app/accounts/templates/my_profile.html
{%extends 'base.html'%}
{%block main_content%}
my profile
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <a href="{%url 'accounts:change-password' request.user.id %}">изменить пароль</a>
    </br>
    </br>
    </br>
    <button type="submit">одтвердить</button>
</form>
{%endblock%}

app/accounts/templates/password_change.html
{%extends 'base.html'%}
{%block main_content%}
<form method="POST">{%csrf_token%}
    смена пароля
    </br>
    </br>
    <input name="old_password" class="form-control" placeholder="старый пароль" type="password">
    </br>
    </br>
    <input name="new_password1" class="form-control" placeholder="новый пароль" type="password">
    </br>
    </br>
    <input name="new_password2" class="form-control" placeholder="подтвердите пароль" type="password">
    </br>
    </br>
    {% for field in form %}
    {% for error in field.errors %}
    <p style="color:red">{{error}}</p>
    {% endfor %}
    {% endfor %}
    <button id="id_submit_btn" type="submit">Подвердить</button>
</form>
{%endblock%}

app/accounts/templates/password_success.html
{%extends 'base.html'%}
{%block main_content%}
Пароль успешно изменён!
{%endblock%}

app/accounts/templates/sing_up.html
{%extends 'base.html'%}
{%block main_content%}
регистрация
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit">зарегистрироваться</button>
</form>
{%endblock%}